### ISSUE TITLE
Where can find bulk_migration.python

### ISSUE THREAD

**Issue by sodiumchl** [unsupported/canvas#121]
master/api/bulk_course_export
course-export.py has the following line (131)
from bulk_migration.python import course_migrations
Where can I find bulk_migration.python?

**Comment by broccolihero13** [comment]
Hi @sodiumchl,

I believe the file you're looking to "import from" on line 131 of /master/api/bulk_course_export is here: https://github.com/unsupported/canvas/tree/master/api/bulk_migration/python

It was written a little while ago so be sure to review the readme and test things thoroughly. Also, I think it's using Python 2.7. A lot could have changed in 4 years since it was uploaded. If you are a Canvas admin, it may also be good to reach out to your Customer Success Manager to see about consultation options.
